



CREATE DATABASE bank_db;
use bank_db;

CREATE TABLE ACCOUNT (num NVARCHAR(50),name NVARCHAR(50), balance money);

INSERT INTO ACCOUNT VALUES ('1', 'Nag', 1000);
INSERT INTO ACCOUNT VALUES ('2', 'Ria', 1000);